name: SkillBridge CI

on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 33066:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: skillbridge
        options: >-
          --health-cmd="mysqladmin ping -h localhost --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, intl, pdo_mysql
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: server/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('server/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Dependencies
        working-directory: ./server
        run: composer install --no-ansi --no-interaction --no-progress --prefer-dist

      - name: Copy .env
        working-directory: ./server
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Update .env for MySQL
        working-directory: ./server
        run: |
          sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=mysql/' .env
          sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' .env
          sed -i 's/DB_PORT=.*/DB_PORT=33066/' .env
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=skillbridge/' .env
          sed -i 's/DB_USERNAME=.*/DB_USERNAME=root/' .env
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=root/' .env

      - name: Generate key
        working-directory: ./server
        run: php artisan key:generate

      - name: Directory Permissions
        working-directory: ./server
        run: chmod -R 777 storage bootstrap/cache

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            mysqladmin ping -h127.0.0.1 --port=33066 --silent && break
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Run migrations
        working-directory: ./server
        run: php artisan migrate --force

      - name: Run tests
        working-directory: ./server
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 33066
          DB_DATABASE: skillbridge
          DB_USERNAME: root
          DB_PASSWORD: root
        run: php artisan test

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: client/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('client/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Build client
        working-directory: ./client
        run: |
          npm install
          npm run build
